name: macOSCI

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:

env:
  BUILD_VERSION: '1.0'
  DOTNET_VERSION: 8.0.x
  DOTNET_VERSION_TARGETS: net8.0
  XCODE_VERSION: '15.2'
  CSPROJ_TO_BUILD: 'GigPayTracker/GigPayTracker.csproj'
  PROJECT_FOLDER: 'GigPayTracker'
  PACKAGE_NAME: 'services.emedia.gigpaytracker'
  BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
  P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
  BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
  KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}

jobs:  
  buildiOS:
    runs-on: macOS-13
    
    steps:
    # SETUP ENVIRONMENT
      - name: Checkout Code
        uses: actions/checkout@v2

      # - uses: maxim-lobanov/setup-xcode@v1
      #   name: Set XCode version
      #   with:
      #     xcode-version: ${{env.XCODE_VERSION}}

      - name: Setup .NET SDK ${{env.DOTNETVERSION}}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version:  '${{env.DOTNET_VERSION}}'

      - name: Install .NET MAUI
        shell: bash
        run: |
          dotnet nuget locals all --clear 
          dotnet workload install maui-android maui-ios
    
      - name: Restore Dependencies
        run: dotnet restore ${{ env.CSPROJ_TO_BUILD }}
        
    # SETUP CERT
      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          # The certificates in a PKCS12 file encoded as a base64 string.
          p12-file-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          # The password used to import the PKCS12 file.
          p12-password: ${{ secrets.P12_PASSWORD }}
          
    # SETUP PROVISIONING
      - name: Download Apple Provisioning Profiles
        # You may pin to the exact commit or the version.
        uses: Apple-Actions/download-provisioning-profiles@v1
        with:
          # The bundle identifier of the application
          bundle-id: ${{ env.PACKAGE_NAME }}
          # The type of profile to download. One of IOS_APP_DEVELOPMENT, IOS_APP_STORE, IOS_APP_ADHOC, IOS_APP_INHOUSE, MAC_APP_DEVELOPMENT, MAC_APP_STORE, MAC_APP_DIRECT, TVOS_APP_DEVELOPMENT, TVOS_APP_STORE, TVOS_APP_ADHOC, TVOS_APP_INHOUSE
          profile-type: 'IOS_APP_STORE'
          # The AppStore Connect API Key Issuer Identifier
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          # The Key ID for AppStore Connect API
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          # The PKCS8 format Private Key for AppStore Connect API
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
          
    # BUILD/PUBLISH APP
        # https://docs.microsoft.com/en-us/dotnet/maui/ios/deployment/overview
      - name : Build iOS App
        shell: bash
        run: dotnet build ${{ env.CSPROJ_TO_BUILD }} -f net8.0-ios -c Release -o ./artifacts

      - name : Publish iOS App
        shell: bash
        run: dotnet publish ${{ env.CSPROJ_TO_BUILD }} -f net8.0-ios -c Release -p:BuildIpa=True -o ./artifacts
